# Generated by Django 3.1 on 2020-11-03 15:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', models.FileField(blank=True, null=True, upload_to='user_cvs', verbose_name='Резюме')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Зарплата в USD')),
                ('patent', models.FileField(blank=True, null=True, upload_to='staff_patents', verbose_name='Патент')),
                ('contract', models.FileField(blank=True, null=True, upload_to='contracts', verbose_name='Скан договора')),
                ('passport_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер паспорта')),
                ('authority', models.CharField(blank=True, max_length=10, null=True, verbose_name='Кем выдан')),
                ('date_of_issue', models.DateField(default=datetime.date.today, verbose_name='Дата выдачи')),
                ('date_of_expire', models.DateField(default=datetime.date.today, verbose_name='Срок действия')),
                ('passport_scan', models.FileField(blank=True, null=True, upload_to='passport_scans', verbose_name='Скан паспорта')),
                ('fired', models.BooleanField(default=False)),
                ('start_work', models.DateField(blank=True, null=True, verbose_name='Дата прихода')),
                ('end_work', models.DateField(blank=True, null=True, verbose_name='Дата ухода')),
                ('end_work_cause', models.TextField(blank=True, null=True, verbose_name='Причина ухода')),
                ('is_hr', models.BooleanField(default=False, verbose_name='HR')),
                ('is_sales', models.BooleanField(default=False, verbose_name='Менеджер по продажам')),
                ('is_marketing', models.BooleanField(default=False, verbose_name='Маркетолог')),
                ('is_finance', models.BooleanField(default=False, verbose_name='Менеджер по финансам')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ('-id',),
            },
        ),
    ]
