# Generated by Django 3.1 on 2020-11-03 15:42

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(db_index=True, max_length=255, verbose_name='Фамилия')),
                ('old_name', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Отчество')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('telephone_number', models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='Телефон должен быть в формате +999[код][номер]', regex='^(\\+996)\\d{9}$')], verbose_name='Телефон')),
                ('contacted_from', models.CharField(choices=[('WHATSAPP', 'WHATSAPP'), ('INSTAGRAM', 'INSTAGRAM'), ('FACEBOOK', 'FACEBOOK'), ('TELEGRAM', 'TELEGRAM'), ('INCOMING', 'INCOMING CALL'), ('WEBSITE', 'WEBSITE'), ('OFFICE', 'OFFICE')], max_length=255, verbose_name='Связался с')),
                ('test', models.BooleanField(blank=True, default=False, null=True, verbose_name='Сдал тест')),
                ('came', models.BooleanField(blank=True, default=False, null=True, verbose_name='Пришел на консультацию')),
                ('obrabotan', models.BooleanField(blank=True, default=False, null=True, verbose_name='Обработан')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарии')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создани')),
                ('otkaz', models.BooleanField(default=False, verbose_name='Oтказ')),
                ('prichina_otkaza', models.TextField(blank=True, verbose_name='Причина отказа')),
                ('paid', models.BooleanField(default=False, verbose_name='Оплатил')),
                ('waiting', models.BooleanField(default=False, verbose_name='Ждет')),
                ('contact_whatsapp', models.BooleanField(default=False, verbose_name='Написал(а) в Whatsapp')),
                ('contact_telegram', models.BooleanField(default=False, verbose_name='Написал(а) в Telegram')),
                ('contact_email', models.BooleanField(default=False, verbose_name='Написал(а) на почту')),
                ('contact_call', models.BooleanField(default=False, verbose_name='Позвонил(а)')),
                ('courses', models.ManyToManyField(blank=True, related_name='clients', to='courses.Course', verbose_name='Интересующие курсы')),
            ],
            options={
                'verbose_name': 'КЛИЕНТ',
                'verbose_name_plural': 'КЛИЕНТЫ',
                'ordering': ('-id',),
            },
        ),
    ]
