# Generated by Django 3.1 on 2020-11-07 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klasses', '0003_klass_base'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klass',
            name='base',
            field=models.CharField(choices=[('11', '11 класс'), ('10', '10 класс'), ('9', '9 класс')], default='9', max_length=255, verbose_name='База'),
        ),
    ]
