export const START_LOADING = 'START_LOADING'
export const STOP_LOADING = 'STOP_LOADING'

export const FETCH_COURSES_SUCCESS = 'FETCH_COURSES_SUCCESS'
export const FETCH_COURSES_ERROR = 'FETCH_COURSES_ERROR'
export const CLEAR_COURSES = 'CLEAR_COURSES'

export const FETCH_KLASSES_SUCCESS = 'FETCH_KLASSES_SUCCESS'
export const FETCH_KLASSES_ERROR = 'FETCH_KLASSES_ERROR'
export const CLEAR_KLASSES = 'CLEAR_KLASSES'

export const FETCH_COURSES_DETAIL = 'FETCH_COURSES_DETAIL'

export const FETCH_COURSES_DETAIL_ERROR = 'FETCH_COURSES_DETAIL_ERROR'
export const FETCH_COURSES_TAGS = 'FETCH_COURSES_TAGS'

export const FETCH_COURSES_TAGS_ERROR = 'FETCH_COURSES_TAGS_ERROR'

export const FETCH_COURSES_PARTNERS = 'FETCH_COURSES_PARTNERS'
export const FETCH_COURSES_PARTNERS_ERROR = 'FETCH_COURSES_PARTNERS_ERROR'

export const FETCH_COURSES_SCOPES = 'FETCH_COURSES_SCOPES'
export const FETCH_COURSES_SCOPES_ERROR = 'FETCH_COURSES_SCOPES_ERROR'

export const FETCH_USERS = 'FETCH_USERS'
export const FETCH_USERS_ERROR = 'FETCH_USERS_ERROR'
export const CLEAR_USERS = 'CLEAR_USERS'

export const GET_CREATED_USER_ID = 'GET_CREATED_USER_ID';
export const FETCH_KLASS_DETAIL_START = 'FETCH_KLASS_DETAIL_START'
export const FETCH_KLASS_DETAIL_SUCCESS = 'FETCH_KLASS_DETAIL_SUCCESS'
export const FETCH_KLASS_DETAIL_ERROR = 'FETCH_KLASS_DETAIL_ERROR'

export const ADD_NEW_FIELDS = 'ADD_NEW_FIELDS';

export const EXPENSES_LIST_GET_REQUEST = 'EXPENSES_LIST_GET_REQUEST'
export const EXPENSES_LIST_GET_REQUEST_ERROR = 'EXPENSES_LIST_GET_REQUEST_ERROR'
export const EXPENSES_DETAIL_GET_REQUEST = 'EXPENSES_DETAIL_GET_REQUEST'
export const EXPENSES_DETAIL_GET_REQUEST_ERROR = 'EXPENSES_DETAIL_GET_REQUEST_ERROR'

export const INCOMES_LIST_GET_REQUEST_ERROR = 'INCOMES_LIST_GET_REQUEST_ERROR'
export const INCOMES_LIST_GET_REQUEST = 'INCOMES_LIST_GET_REQUEST'
export const INCOMES_DETAIL_GET_REQUEST = 'INCOMES_DETAIL_GET_REQUEST'
export const INCOMES_DETAIL_GET_REQUEST_ERROR = 'INCOMES_DETAIL_GET_REQUEST_ERROR'

export const STUDENT_PAYMENTS_LIST_GET_REQUEST_ERROR = 'STUDENT_PAYMENTS_LIST_GET_REQUEST_ERROR'
export const STUDENT_PAYMENTS_LIST_GET_REQUEST = 'STUDENT_PAYMENTS_LIST_GET_REQUEST'
export const STUDENT_PAYMENTS_DETAIL_GET_REQUEST = 'STUDENT_PAYMENTS_DETAIL_GET_REQUEST'
export const STUDENT_PAYMENTS_DETAIL_GET_REQUEST_ERROR = 'STUDENT_PAYMENTS_DETAIL_GET_REQUEST_ERROR'

export const WALLET_LIST_GET_REQUEST = 'WALLET_LIST_GET_REQUEST'
export const WALLET_LIST_GET_REQUEST_ERROR = 'WALLET_LIST_GET_REQUEST_ERROR'
export const WALLET_DETAIL_GET_REQUEST = 'WALLET_DETAIL_GET_REQUEST'
export const WALLET_DETAIL_GET_REQUEST_ERROR = 'WALLET_DETAIL_GET_REQUEST_ERROR'


export const TRANSACTIONS_LIST_GET_REQUEST = 'TRANSACTIONS_LIST_GET_REQUEST'
export const TRANSACTIONS_LIST_GET_REQUEST_ERROR = 'TRANSACTIONS_LIST_GET_REQUEST_ERROR'
export const TRANSACTIONS_DETAIL_GET_REQUEST = 'TRANSACTIONS_DETAIL_GET_REQUEST'
export const TRANSACTIONS_DETAIL_GET_REQUEST_ERROR = 'TRANSACTIONS_DETAIL_GET_REQUEST_ERROR'
export const CLEAR_TRANSACTIONS = 'CLEAR_TRANSACTIONS'

export const EXPENSES_TAGS_GET_REQUEST = 'EXPENSES_TAGS_GET_REQUEST'
export const EXPENSES_TAGS_GET_REQUEST_ERROR = 'EXPENSES_TAGS_GET_REQUEST_ERROR'

export const STUDENTS_LIST_GET_REQUEST = 'STUDENTS_LIST_GET_REQUEST'
export const STUDENTS_LIST_GET_REQUEST_ERROR = 'STUDENTS_LIST_GET_REQUEST_ERROR'
export const STUDENT_DETAIL_GET_REQUEST = 'STUDENT_DETAIL_GET_REQUEST'
export const STUDENT_DETAIL_GET_REQUEST_ERROR = 'STUDENT_DETAIL_GET_REQUEST_ERROR'

export const FETCH_EXAMS_START = "FETCH_EXAMS_START";
export const FETCH_EXAMS_SUCCESS = "FETCH_EXAMS_SUCCESS";
export const FETCH_EXAMS_ERROR = "FETCH_EXAMS_ERROR";
export const SET_EXAMS_RESULTS_ID = "SET_EXAMS_RESULTS_ID";

export const FETCH_BRANCHES_SUCCESS = 'FETCH_BRANCHES_SUCCESS';
export const FETCH_BRANCHES_ERROR = 'FETCH_BRANCHES_ERROR';

export const FETCH_INVENTORIES = 'FETCH_INVENTORIES'
export const FETCH_INVENTORIES_ERROR = 'FETCH_INVENTORIES_ERROR'
export const CLEAR_INVENTORIES = 'CLEAR_INVENTORIES'

export const PERSONAL_DATA = 'PERSONAL_DATA'
export const PERSONAL_DATA_ERROR = 'PERSONAL_DATA_ERROR'
export const FETCHED_PERSONAL_DATA = 'FETCHED_PERSONAL_DATA'
export const FETCHED_PERSONAL_DATA_ERROR = 'FETCHED_PERSONAL_DATA_ERROR'

export const SET_BREADCRUMBS = 'SET_BREADCRUMBS'
export const CLEAR_BREADCRUMBS = 'CLEAR_BREADCRUMBS'