# Generated by Django 3.1 on 2020-11-03 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='partner',
        ),
        migrations.RemoveField(
            model_name='course',
            name='scopes',
        ),
        migrations.DeleteModel(
            name='Partner',
        ),
        migrations.DeleteModel(
            name='Scope',
        ),
    ]
