# Generated by Django 3.1 on 2020-11-04 20:10

from django.db import migrations, models
import utils.generators


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.generators.generate_image_filename, verbose_name='Изображение'),
        ),
    ]
