# Generated by Django 3.1 on 2020-11-03 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrators', '0004_administrator_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrator',
            name='branch',
        ),
    ]
