# Generated by Django 3.1 on 2020-11-06 15:43

from django.db import migrations, models
import utils.generators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201106_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=utils.generators.generate_image_filename, verbose_name='Фото профиля'),
        ),
    ]
