# Generated by Django 3.1 on 2020-11-03 15:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('exam_type', models.CharField(choices=[('E', 'Entrance'), ('M', 'Midterm'), ('F', 'Final')], max_length=16)),
            ],
            options={
                'verbose_name': 'Экзамен',
                'verbose_name_plural': 'ЭКЗАМЕНЫ',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('question_type', models.CharField(choices=[('R', 'radio button'), ('C', 'check box'), ('ST', 'short text'), ('LT', 'long text'), ('F', 'file field'), ('S', 'scale'), ('D', 'date'), ('T', 'time')], max_length=16)),
            ],
            options={
                'verbose_name': 'ВОПРОС',
                'verbose_name_plural': 'ВОПРОСЫ',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1024, null=True)),
                ('is_correct', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'ОТВЕТ НА ЭКЗАМЕН',
                'verbose_name_plural': 'ОТВЕТЫ НА ЭКЗАМЕН',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False)),
                ('answer_text', models.TextField(blank=True, null=True)),
                ('additional_file', models.FileField(blank=True, null=True, upload_to='exams/answers/')),
            ],
            options={
                'verbose_name': 'ОТВЕТ ПОЛЬЗОВАТЕЛЯ',
                'verbose_name_plural': 'ОТВЕТЫ ПОЛЬЗОВАТЕЛЕЙ',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='UserCheckBoxAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'ОТВЕТ ФЛАЖКА ПОЛЬЗОВАТЕЛЯ',
                'verbose_name_plural': 'ОТВЕТЫ НА ФЛАЖКИ ПОЛЬЗОВАТЕЛЯ',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='UserExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=128)),
                ('grade', models.PositiveIntegerField(blank=True, null=True)),
                ('checked', models.BooleanField(default=False)),
                ('first_name', models.CharField(blank=True, max_length=128, null=True)),
                ('last_name', models.CharField(blank=True, max_length=128, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(message='Телефон должен быть в формате +999[код][номер]', regex='^(\\+996)\\d{9}$')])),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_exams', to='exams.exam')),
            ],
            options={
                'verbose_name': 'ПОЛЬЗОВАТЕЛЬСКИЙ ЭКЗАМЕН',
                'verbose_name_plural': 'ПОЛЬЗОВАТЕЛЬСКИЕ ЭКЗАМЕНЫ',
                'ordering': ('-id',),
            },
        ),
    ]
