# Generated by Django 3.1 on 2020-11-05 19:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_auto_20201103_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userexam',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(message='Телефон должен быть в формате +996[код][номер]', regex='^(\\+996)\\d{9}$')]),
        ),
    ]
