# Generated by Django 3.1 on 2020-11-08 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_auto_20201106_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.TextField(verbose_name='Вопрос'),
        ),
    ]
