# Generated by Django 3.1 on 2020-11-08 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_exam_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='attachment_file',
            field=models.FileField(blank=True, null=True, upload_to='exams/questions/'),
        ),
    ]
