# Generated by Django 3.1 on 2020-12-27 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_question_attachment_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
