# Generated by Django 3.1 on 2020-12-30 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_exam_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='time_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
