# Generated by Django 3.1 on 2020-11-03 18:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Название')),
                ('oblast', models.CharField(choices=[('IK', 'Иссык-Кульская область'), ('CH', 'Чуйская область'), ('NR', 'Нарынская область'), ('TS', 'Таласская область'), ('OS', 'Ошская область'), ('JL', 'Джалал-Абадская область'), ('BT', 'Баткенская область')], max_length=255, verbose_name='Область')),
                ('city', models.CharField(max_length=255, verbose_name='Город или населенный пункт')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта')),
                ('telephone_number', models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='Телефон должен быть в формате +999[код][номер]', regex='^(\\+996)\\d{9}$')], verbose_name='Телефон')),
                ('description', models.TextField(verbose_name='Описание')),
                ('class9', models.BooleanField(default=True, verbose_name='9-класс')),
                ('class10', models.BooleanField(default=True, verbose_name='10-ый класс')),
                ('class11', models.BooleanField(default=True, verbose_name='11-ый класс')),
            ],
            options={
                'verbose_name': 'Филиал',
                'verbose_name_plural': 'Филиалы',
                'ordering': ['id'],
            },
        ),
    ]
