# Generated by Django 3.1 on 2021-01-14 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_auto_20201106_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='for_superusers',
            field=models.BooleanField(default=False, verbose_name='Для суперпользователей'),
        ),
    ]
