# Generated by Django 3.1 on 2020-11-03 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0002_trainer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='patent',
        ),
    ]
