# Generated by Django 3.1 on 2020-11-03 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0003_remove_trainer_patent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='interview_comments',
        ),
    ]
