# Generated by Django 3.1 on 2020-11-03 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('trainers', '0004_remove_trainer_interview_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainers', to='branches.branch', verbose_name='Филиал'),
        ),
    ]
