# Generated by Django 3.1 on 2020-11-03 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0005_trainer_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='branch',
        ),
    ]
