# Generated by Django 3.1 on 2020-11-06 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0008_trainer_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='avatar',
        ),
    ]
