# Generated by Django 3.1 on 2020-11-03 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('klasses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Название темы')),
                ('day', models.DateField(verbose_name='Дата события')),
                ('material', models.FileField(blank=True, null=True, upload_to='material', verbose_name='Материал темы')),
                ('start_time', models.TimeField(verbose_name='Время начало урока')),
                ('end_time', models.TimeField(verbose_name='Время до конца урока')),
                ('homework_link', models.URLField(verbose_name='Ссылка на домашние задание')),
                ('klass', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='klasses.klass', verbose_name='Класс')),
            ],
            options={
                'verbose_name': 'ГРАФИК',
                'verbose_name_plural': 'ГРАФИКИ',
                'ordering': ('-id',),
            },
        ),
    ]
