# Generated by Django 3.1 on 2020-11-04 20:10

from django.db import migrations, models
import utils.generators


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='material',
            field=models.FileField(blank=True, null=True, upload_to='material', verbose_name=utils.generators.generate_document_filename),
        ),
    ]
