# Generated by Django 3.1 on 2020-09-28 10:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=256)),
                ('amount', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Inventory categories',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, db_index=True, max_length=6, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]+$')])),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventories', to='inventories.inventorycategory')),
            ],
            options={
                'verbose_name_plural': 'Inventories',
            },
        ),
    ]
