# Generated by Django 3.1 on 2020-11-08 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_auto_20201106_0146'),
        ('inventories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'ordering': ['-id'], 'verbose_name': 'Инвентарь', 'verbose_name_plural': 'Инвентари'},
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='number',
        ),
        migrations.AddField(
            model_name='inventory',
            name='amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch', verbose_name='Филиал'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарии'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100, verbose_name='Стоимость за 1 штуку'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='title',
            field=models.CharField(default='', max_length=255, verbose_name='Название инвентаря'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='InventoryCategory',
        ),
    ]
