# Generated by Django 3.1 on 2020-11-09 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0002_auto_20201109_0528'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='inventory_number',
            field=models.CharField(blank=True, max_length=255, verbose_name='Номер идентификации'),
        ),
    ]
