# Generated by Django 3.1 on 2020-11-03 15:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория расхода',
                'verbose_name_plural': 'Категории расходов',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_id', models.CharField(blank=True, db_index=True, max_length=255, unique=True, verbose_name='ID кошелька')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Наименование кошелька')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('privacy', models.CharField(choices=[('PRIVATE', 'Приватный кошелек'), ('PUBLIC', 'Публичный кошелек')], default='PRIVATE', max_length=255, verbose_name='Приватность')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=100, verbose_name='Баланс счета')),
                ('account_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер счета')),
            ],
            options={
                'verbose_name': 'Кошелёк',
                'verbose_name_plural': 'Кошельки',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Наименование транзакции')),
                ('transaction_id', models.CharField(blank=True, db_index=True, max_length=255, unique=True, verbose_name='ID транзакции')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=100, verbose_name='Сумма')),
                ('confirmation', models.FileField(blank=True, null=True, upload_to='finances/confirmations', verbose_name='Прикрепите фото или скан чека')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарии')),
                ('method', models.CharField(blank=True, choices=[('TRANSFER', 'Трансфер'), ('DEPOSIT', 'Пополнение')], max_length=255, null=True, verbose_name='Метод')),
                ('transaction_type', models.CharField(choices=[('INCOME', 'Доход'), ('EXPENSE', 'Расход'), ('STUDENT', 'Оплата студента')], max_length=10, verbose_name='Тип транзакции')),
                ('categories', models.ManyToManyField(blank=True, related_name='transactions', to='finances.ExpenseTag', verbose_name='Категории расхода')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='courses.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
                'ordering': ['-id'],
            },
        ),
    ]
