# Generated by Django 3.1 on 2020-11-03 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='students.student', verbose_name='Студент'),
        ),
    ]
