# Generated by Django 3.1 on 2020-11-04 20:10

from django.db import migrations, models
import utils.generators


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_auto_20201103_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='confirmation',
            field=models.FileField(blank=True, null=True, upload_to=utils.generators.generate_document_filename, verbose_name='Прикрепите фото или скан чека'),
        ),
    ]
