# Generated by Django 3.1 on 2020-11-04 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('finances', '0004_auto_20201105_0210'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='branches.branch', verbose_name='Филиал'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallets', to='branches.branch', verbose_name='Филиал'),
        ),
    ]
