# Generated by Django 3.1 on 2020-11-03 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20201103_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='student',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='student',
            name='favorite_books',
        ),
        migrations.RemoveField(
            model_name='student',
            name='favorite_games',
        ),
        migrations.RemoveField(
            model_name='student',
            name='favorite_heros',
        ),
        migrations.RemoveField(
            model_name='student',
            name='favorite_movies',
        ),
        migrations.RemoveField(
            model_name='student',
            name='favorite_music',
        ),
        migrations.RemoveField(
            model_name='student',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='student',
            name='hobbies',
        ),
        migrations.RemoveField(
            model_name='student',
            name='interview_url',
        ),
        migrations.RemoveField(
            model_name='student',
            name='motivation',
        ),
        migrations.RemoveField(
            model_name='student',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='student',
            name='position',
        ),
        migrations.RemoveField(
            model_name='student',
            name='study_hours',
        ),
        migrations.RemoveField(
            model_name='student',
            name='study_place',
        ),
        migrations.RemoveField(
            model_name='student',
            name='tshirt_size',
        ),
        migrations.RemoveField(
            model_name='student',
            name='work_place',
        ),
        migrations.DeleteModel(
            name='History',
        ),
    ]
