# Generated by Django 3.1 on 2020-11-05 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_remove_student_graduation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='finish_date',
            field=models.DateField(null=True, verbose_name='Дата окончания учебы'),
        ),
    ]
