# Generated by Django 3.1 on 2020-11-06 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_auto_20201106_0157'),
        ('students', '0007_student_avatar'),
    ]

    operations = [
    ]
