# Generated by Django 3.1 on 2021-01-20 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_auto_20201208_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='english_level',
            field=models.CharField(blank=True, choices=[('B', 'Beginner'), ('E', 'Elementary'), ('I', 'Intermediate'), ('A', 'Advanced')], max_length=100, null=True, verbose_name='Уровень английского'),
        ),
    ]
