# Generated by Django 3.1 on 2021-01-20 18:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import utils.generators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0003_branch_for_superusers'),
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Описание')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время')),
                ('for_all', models.BooleanField(default=False, verbose_name='Для всех филиалов')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='branches.branch', verbose_name='Для филиала')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=utils.generators.generate_image_filename, verbose_name='Изображение')),
                ('new', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.new', verbose_name='Новость')),
            ],
            options={
                'verbose_name': 'Изображение для новости',
                'verbose_name_plural': 'Изображения для новостей',
            },
        ),
    ]
