# Generated by Django 3.1 on 2021-01-20 19:16

from django.db import migrations, models
import django.db.models.deletion
import utils.generators


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_branch_for_superusers'),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.generators.generate_image_filename, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='new',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news', to='branches.branch', verbose_name='Для филиала'),
        ),
        migrations.DeleteModel(
            name='NewsImage',
        ),
    ]
